apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/maistraoperator.openshift-operators: ""
  name: maistraoperator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: maistraoperator
  source: community-operators
  sourceNamespace: openshift-marketplace